# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [1]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [5]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Vertical stacking - Increasing the number of row
arr_3=np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [10]:
# Checking the dimensions of the array
arr_3.ndim

2

In [9]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
# Number of rows and columns in the array
arr_3.shape  

(2, 5)

### Reshaping

In [12]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(10)

# Printing the created array
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [14]:
# Checking the rows and columns in the created array
arr_5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [17]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [20]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [21]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = np.arange(20,40).reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [22]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [34]:
x=np.array(range(1, 11*12+1))
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

In [35]:
x=np.array(range(1, 11*12+1)).reshape(11,12)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [40]:
print(x[9,8])

117


In [41]:
np.unravel_index(99, (11,12))

(8, 3)

In [42]:
print(x[8,3])

100


In [43]:
y=[[1, 5],
 [3, 7],
 [4, 9]]

y

[[1, 5], [3, 7], [4, 9]]

In [44]:
y=np.array(y)

In [45]:
y

array([[1, 5],
       [3, 7],
       [4, 9]])

In [47]:
np.reshape(y, -1)

array([1, 5, 3, 7, 4, 9])

reshape() function returns a 1-D array when you specify the shape as -1.

In [52]:
array_1=np.arange(1,21).reshape(4,5)
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
print(array_1.reshape(5, 4)[array_1%2 != 0])

ValueError: operands could not be broadcast together with shapes (5,4) (4,5) 

In [54]:
print(array_1[array_1%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [55]:
print(array_1[array_1%2 == 0].reshape(5, 2))

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [56]:
print(array_1[array_1%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [57]:
p=[[1, 5],
 [3, 7],
 [4, 9]]

p

[[1, 5], [3, 7], [4, 9]]

In [58]:
P=np.array(p)

In [59]:
P

array([[1, 5],
       [3, 7],
       [4, 9]])

In [60]:
np.reshape(P, (1, -1))

array([[1, 5, 3, 7, 4, 9]])